### ISSUE TITLE
StreamApi.test.js test suite failure "lockfileVersion":2.

### ISSUE THREAD

**Issue by ButlerJAL** [bean-pod/switchboard#210]
**Operating system:**

- macOS 10.16
- IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
- Node 15.5.1
- npm 6.14.11

**Steps to reproduce:**

1. open a terminal.
2. cd into project's /frontend directory.
3. run `npm test` command.

**Expected result:**
21/21 test suites should pass.

**Actual result:**
20/21 test suites pass, but the tests themselves in the failing test suite are passing... I've investigated. And, in summary, the error has to do with throwing inside of an async function without a catch block (lack of error handling). For example, the DeviceApi test suite has similar tests with error handling, and I get no errors there. I don't really understand the whole asynchronous callback testing going on, but hopefully someone that does could add error handling to the test suite in order to fix the bug I am experiencing. Else, I could still compile and run locally.

**Visual proof:**
 
|  Actual  |
|:---------------:|
| ![Screen Shot 2021-01-08 at 1 57 23 PM](https://user-images.githubusercontent.com/35884919/104070529-18269e00-51d5-11eb-9388-fa98b5276cb9.png)
![Screen Shot 2021-01-08 at 5 25 01 PM](https://user-images.githubusercontent.com/35884919/104071126-7c962d00-51d6-11eb-9b32-4bd62a315a2c.png) |

| Expected |
|:---------------:|
| ![image](https://user-images.githubusercontent.com/35884919/104072028-4e195180-51d8-11eb-925b-873de29ce31b.png) |

**Comment by ButlerJAL** [comment]
I narrowed down the cause of why this bug seems isolated to me.

I had a higher version of node/npm that introduced "lockfileVersion":2 on my system.

I downgraded to node@14.15.1 and npm@6.14.9 as used by our GitHub actions runners which uses “lockfileVersion”:1, and all test suites are passing locally now.

If we won't fix this bug, caution must be exercised to avoid versions of node/npm with "lockfileVersion":2.

**Comment by ButlerJAL** [comment]
Closing this issue because it's been fixed. I was able to `npm install` and `npm test` using the latest version of node/npm (node 15.12.0 & npm 7.6.3) without issues. I show the console log of the tests running successfully on my system below as proof.

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js test --scripts-prepend-node-path=auto

> switchboard_frontend@0.1.0 test
> react-scripts test
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
 PASS  src/createStream/__tests__/StreamingTable.test.jsx (6.449 s)
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsConciseRow.test.jsx (6.538 s)
 PASS  src/streamlist/__tests__/StreamsTable.test.jsx (6.647 s)
 PASS  src/homepage/__tests__/HomePageContents.test.jsx (6.973 s)
 PASS  src/general/__tests__/DeleteDeviceButton.test.jsx
 PASS  src/api/tests/StreamApi.test.js
 PASS  src/general/__tests__/PathNotFoundPage.test.jsx
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsTabTable.test.jsx
 PASS  src/deviceDetailsPage/__tests__/DeviceName.test.jsx
 PASS  src/streamDetails/__tests__/StreamDetailsPageContents.test.jsx
 PASS  src/app/__tests__/AppRouter.test.jsx
 PASS  src/api/tests/AuthenticationUtil.test.js
 PASS  src/app/__tests__/ProtectedRoute.test.jsx
 PASS  src/login/__tests__/LoginPageContent.test.jsx
 PASS  src/devicelist/__tests__/DeviceListTabTable.test.jsx
 PASS  src/homepage/__tests__/ActiveStreamCard.test.jsx
 PASS  src/model/__tests__/ConvertDataFormat.test.js
 PASS  src/api/tests/DeviceApi.test.js
 PASS  src/api/tests/LogApi.test.js
 PASS  src/streamDetails/__tests__/StreamDetailsPage.test.jsx
 PASS  src/homepage/__tests__/AdminPanelCard.test.jsx
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsPage.test.jsx
 PASS  src/general/__tests__/HeaderBar.test.jsx
 PASS  src/homepage/__tests__/DevicesCard.test.jsx
 PASS  src/app/__tests__/AdminProtectedRoute.test.jsx
 PASS  src/devicelist/__tests__/ChannelDetailsTableRow.test.jsx
 PASS  src/deviceDetailsPage/__tests__/EditableName.test.jsx
 PASS  src/homepage/__tests__/ActivityLogCard.test.jsx
 PASS  src/streamDetails/__tests__/DeleteStreamDialog.test.jsx
  ● Console

    console.error
      Warning: Failed prop type: The prop `history.go` is marked as required in `DeleteStreamDialog`, but its value is `undefined`.
          in DeleteStreamDialog (at DeleteStreamDialog.test.jsx:36)

      34 |     });
      35 |     wrapper = Enzyme.shallow(
    > 36 |       <DeleteStreamDialog deleteId={dummyId} history={dummyHistory} />
         |       ^
      37 |     );
      38 |   });
      39 |   afterEach(() => {

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:125:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:92:5)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:314:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:758:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:878:7)
      at Object.<anonymous> (src/streamDetails/__tests__/DeleteStreamDialog.test.jsx:36:7)

 PASS  src/general/dialog/__tests__/Dialog.test.jsx
 PASS  src/streamDetails/__tests__/StreamDeviceDetails.test.jsx
 PASS  src/general/__tests__/Page.test.jsx
 PASS  src/streamDetails/__tests__/DeleteStreamDialogOpener.test.jsx
 PASS  src/api/tests/AuthenticationApi.test.js
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsTabPanels.test.jsx
 PASS  src/streamlist/__tests__/StreamDetailsButton.test.jsx
 PASS  src/general/__tests__/Title.test.jsx
 PASS  src/streamlist/__tests__/StreamsTableWrapper.test.jsx
 PASS  src/loglist/__tests__/LogsTableWrapper.test.jsx
 PASS  src/general/__tests__/TitleButtons.test.jsx
 PASS  src/deviceDetailsPage/__tests__/StaticName.test.jsx
 PASS  src/devicelist/__tests__/DevicesTable.test.jsx
 PASS  src/login/__tests__/LoginConsole.test.jsx
 PASS  src/general/dashboard/__tests__/GridColumn.test.jsx
 PASS  src/general/dashboard/__tests__/DashboardButton.test.jsx
 PASS  src/general/__tests__/HorizontalTabPanel.test.jsx
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsConciseTable.test.jsx
 PASS  src/devicelist/__tests__/DeviceListPage.test.jsx
 PASS  src/devicelist/__tests__/ChannelDetailsTableHead.test.jsx
 PASS  src/general/dialog/__tests__/DialogButtons.test.jsx
 PASS  src/streamlist/__tests__/StreamListPage.test.jsx
 PASS  src/devicelist/__tests__/ActionMenu.test.jsx
 PASS  src/general/dashboard/__tests__/DashboardCard.test.jsx
 PASS  src/createStream/__tests__/CreateStreamPage.test.jsx
 PASS  src/deviceDetailsPage/__tests__/DeviceDetailsPageContents.test.jsx
 PASS  src/loglist/__tests__/LogListPage.test.jsx
 PASS  src/loglist/__tests__/LogsTable.test.jsx
 PASS  src/homepage/__tests__/HomePage.test.jsx
 PASS  src/login/__tests__/LoginFailedDialog.test.jsx
 PASS  src/general/dialog/__tests__/DialogBody.test.jsx
 PASS  src/model/__tests__/DeviceInfo.test.jsx
 PASS  src/__tests__/DefaultMakeStylesTheme.test.js
 PASS  src/login/__tests__/LoginPage.test.jsx
  ● Console

    console.error
      Warning: Failed prop type: The prop `history` is marked as required in `LoginPageContents`, but its value is `undefined`.
          in LoginPageContents (at LoginPage.jsx:12)

      10 |   return (
      11 |     <Page title="Login" breadcrumbs={[]}>
    > 12 |       <LoginPageContents history={history} />
         |       ^
      13 |     </Page>
      14 |   );
      15 | }

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:125:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:92:5)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:314:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:758:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:878:7)
      at LoginPage (src/login/LoginPage.jsx:12:7)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
      at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:642:26)

 PASS  src/streamDetails/__tests__/StreamLogs.test.jsx
 PASS  src/__tests__/index.test.jsx

Test Suites: 65 passed, 65 total
Tests:       327 passed, 327 total
Snapshots:   0 total
Time:        21.472 s
Ran all test suites.

Watch Usage: Press w to show more.

```
